[profile.default]
src = "contracts/src"
out = "out"
test = "contracts/test"
script = "contracts/script"
libs = ["lib"]

solc = "0.8.32"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
