[profile.default]
src = "contracts/src"
out = "out"
test = "contracts/test"
script = "contracts/script"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
